Repository maidelrego/Final_Project, pull requests merged in 2020-05, with the labels that each got.

#2 Saphi
  README.md
Labels: documentation

#3 created schema for quote with validators, except address
  models/book.js
  models/index.js
  models/quote.js
  package-lock.json
  package.json
Labels: enhancement

#4 linter in place
  package-lock.json
  package.json
  server.js
Labels: good first issue

#5 Add files via upload
  client/src/images/easter-blue.jpg
Labels: enhancement

#8 Maydelrego
  client/debug.log
  client/src/App.js
  client/src/components/NavBar/MyNav.js
  client/src/components/NavBar/myNav.scss
  client/src/components/Parallax/MyParallax.js
  client/src/components/Quote/Form.2.js
  client/src/components/Quote/Form1.js
  client/src/components/Quote/Form3.js
  client/src/components/Quote/Form4.js
  client/src/components/Quote/Form5.js
  client/src/components/Quote/Form6.js
  client/src/components/Quote/Quote.js
  client/src/components/Quote/form1.css
  client/src/components/Quote/form1.scss
  client/src/components/Quote/form2.scss
  client/src/components/Quote/form6.css
  client/src/components/Selection/Selection.js
  client/src/components/Selection/Test.js
  client/src/components/Selection/selection.scss
  client/src/components/Selection/test.scss
  client/src/components/TypingEffect/TypingEffect.js
  client/src/components/TypingEffect/typing.css
  client/src/images/logo.png
  client/src/pages/Gallery/Gallery.js
  client/src/utils/GlobalState.js
  models/quote.js
Labels: Good & Working, enhancement

#9 Saphi
  .env
  .eslintignore
  .eslintrc.json
  client/.env
  client/.eslintignore
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/.env
  client/src/components/Quote/Form6.js
  client/src/utils/API.js
  controllers/booksController.js
  controllers/quoteController.js
  models/quote.js
  package-lock.json
  package.json
  routes/api/books.js
  routes/api/index.js
  routes/api/quotes.js
  scripts/seedDB.js
  server.js
Labels: Good & Working

#10 Saphi
  client/src/App.js
  client/src/components/NavBar/MyNav.js
  client/src/components/NavBar/index.js
  client/src/components/NavBar/myNav.scss
  client/src/components/Parallax/MyParallax.js
  client/src/pages/Contact Us/index.js
  client/src/pages/Gallery/gallery.css
  client/src/pages/Gallery/index.js
  server.js
Labels: enhancement

#14 quote validation fully working
  client/src/App.js
  client/src/components/Quote/Form.2.js
  client/src/components/Quote/Form1.js
  client/src/components/Quote/Form3.js
  client/src/components/Quote/Form4.js
  client/src/components/Quote/Form5.js
  client/src/components/Quote/Form6.js
  client/src/components/Quote/form1.css
  client/src/components/Quote/form2.scss
  client/src/components/Quote/form3.scss
  client/src/components/Quote/form4.scss
  client/src/components/Quote/form5.scss
  client/src/components/Quote/form6.css
  client/src/pages/Admin/Admin.js
  client/src/pages/Admin/admin.css
  client/src/pages/NoMatch/NoMatch.js
  client/src/pages/Quote/Quote.js
  client/src/pages/Quote/QuoteDetails.js
  client/src/pages/Quote/quote.scss
Labels: Good & Working

#20 Local time, NoMatch Route, About Us Navlink
  .gitignore
  client/.gitignore
  client/package-lock.json
  client/src/App.js
  client/src/components/NavBar/NavBar.js
  client/src/pages/Admin/Admin.js
  client/src/pages/NoMatch/NoMatch.js
  client/src/pages/Quote/Quote.js
  models/quote.js
  models/quote/quote.js
  package-lock.json
  package.json
  scripts/seedDB.js
Labels: Good & Working

#23 Maydelrego
  client/src/App.js
  client/src/components/About/about.css
  client/src/index.css
  client/src/pages/Admin/Admin.js
  client/src/pages/Admin/admin.css
  client/src/pages/Quote/Quote.js
  client/src/pages/Quote/quote.scss
  models/quote/quote.js
Labels: Good & Working

#28 Saphi
  client/src/App.js
  client/src/components/NavBar/NavBar.js
  client/src/pages/Quote/Quote.js
  package.json
Labels: Good & Working
